# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: filestream
  paths:
    - /var/log/bookface/bf_uc_reports_clerk.log
  fields:
    index_template: logs-bf_uc_reports_clerk

- type: filestream
  paths:
    - /var/log/bookface/bf_uc_reports_leeshore.log
  fields:
    index_template: logs-bf_uc_reports_leeshore

- type: filestream
  paths:
    - /var/log/bookface/bf_uc_reports_webcheck.log
  fields:
    index_template: logs-bf_uc_reports_webcheck

- type: filestream
  paths:
    - /var/log/bookface/bf_uc_reports_webuse.log
  fields:
    index_template: logs-bf_uc_reports_webuse

- type: filestream
  paths:
    - /var/log/bookface/bf_uc_reports_continuous.log
  fields:
    index_template: logs-bf_uc_reports_continuous

# ============================== Filebeat modules ==============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ======================= Elasticsearch template setting =======================
setup.template.settings:
  index.number_of_shards: 1

# =================================== Kibana ===================================
setup.kibana:

# ================================== Outputs ===================================
# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["https://192.168.128.252:9200"]

  # Protocol - either `http` (default) or `https`.
  protocol: "https"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "elastic"
  password: "superuser"
  ssl.certificate_authorities: ["/home/ubuntu/elasticsearch-ca.pem"]

  data_stream:
     type: "filestream"
     dataset: "{{fields.index_template}}"

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# ================================== Logging ===================================
logging.level: debug
logging.selectors: ["*"]


